// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  All SceMi types
// Generated on: Tue Sep 05 03:11:59 IST 2017
// Bluespec version: 2017.04.beta1 2017-04-17 35065

#pragma once

#include "PowerStruct.h" 
#include "PowerAssoc.h" 
#include "ProbeControl.h" 
#include "PrbNum.h" 
#include "CosimStruct.h" 
#include "Flit.h" 
#include "PowerProbe.h" 
#include "PwPrbKind.h" 
#include "SimulationControlReq.h" 
#include "SimulationStatusResp.h" 
#include "Mem_data_t.h" 
#include "Tag.h" 
#include "TLPFirstDWBE.h" 
#include "TLPLastDWBE.h" 
#include "ByteCount.h" 
#include "CreditCount.h" 
#include "DestAddr.h" 
#include "VCType.h" 
#include "FlitData.h" 
#include "RecvPortId.h" 
#include "PortId.h" 
#include "SourceAddr.h" 
#include "ClkNextRdy.h" 
