// This file automatically generated by SceMiParams::genProbeFile
// DO NOT EDIT
// Generated on: Tue Sep 05 03:11:58 IST 2017
// Bluespec version: 2017.04.beta1 2017-04-17 35065

#include "bsv_scemi.h"


BSVType *ProbesXactor::createData(unsigned int probeNum, Packet *data, SceMiU64 cycle)
{
  BSVType *type = NULL;
 // No probes are defined!

  return type;
}

unsigned int ProbesXactor::getBitSize(unsigned int probeNum)
{
  return 0;
}

