// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  SceMiXactors::SimulationStatusResp
// Generated on: Tue Sep 05 03:11:58 IST 2017
// Bluespec version: 2017.04.beta1 2017-04-17 35065

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<32> to SimulationStatusResp
typedef BitT<32> SimulationStatusResp ;

