// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  NATypes::VCType
// Generated on: Tue Sep 05 03:11:59 IST 2017
// Bluespec version: 2017.04.beta1 2017-04-17 35065

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<1> to VCType
typedef BitT<1> VCType ;

